In [1]:
import pandas as pd
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
np.arange(1,10,3)              #np.arange(start,stop,step)

array([1, 4, 7])

In [8]:
np.linspace(0,2,9)                    #Add evenly spaced values btw interval to array of length

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
np.zeros((3,3))                  #	Create and array filled with zeros(row,colm)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((1,2))                      #Creates an array filled with ones

array([[1., 1.]])

In [14]:
np.random.random((5,3))                          #	Creates random array(row,colm)

array([[0.69230066, 0.12408108, 0.55499059],
       [0.99891547, 0.73094722, 0.55105072],
       [0.81033498, 0.02680483, 0.56679829],
       [0.06869249, 0.59361345, 0.2100265 ],
       [0.59582342, 0.21077287, 0.06635544]])

In [15]:
np.empty((2,2))                        #	Creates an empty array

array([[2.12199579e-314, 1.04189993e-311],
       [1.60077269e-321, 1.04189993e-311]])

In [18]:
array  = np.array([(1,2,3),(4,5,6)])

In [19]:
array.shape    #	Dimensions (Rows,Columns)

(2, 3)

In [20]:
len(array)             #	Length of Array

2

In [21]:
array.ndim                    #	Number of Array Dimensions (each colm is a dimension)

2

In [28]:
array.dtype            #	Data Type

dtype('int32')

In [32]:
array.astype(str)              #	Converts to Data Type

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [33]:
type(array)            #	Type of Array

numpy.ndarray

In [48]:
a=3
b=4


array = np.append(a,b)             #	Append items to array
array

array([3, 4])

In [41]:
np.insert(array, 1, 2, axis = 0)               #	Insert items into array at axis 0 or 1

array([3, 2, 4])

In [68]:
array  = np.array([(1,2,3),(4,5,6)])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.insert(array, 2, 3, axis = 1)        # (array, position(index) ,element which we want to insert , axis(row / colm))
                                           # index start from 0

array([[1, 2, 3, 3],
       [4, 5, 3, 6]])

In [57]:
np.resize(array,(2,4))                 #	Resize array to shape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 1, 2]])

In [60]:
np.delete(array,1, axis = 0)   #	Deletes items from array(array_name , index_position)

array([[1, 2, 3]])

In [61]:
np.copy(array)       #	Creates copy of array

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
other = array.copy()          #	Creates deep copy of array
other

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
array  = np.array([(1,6,3),(4,3,6)])
array

array([[1, 6, 3],
       [4, 3, 6]])

In [81]:
array.sort()                   #	Sorts an array
array

array([[1, 3, 6],
       [3, 4, 6]])

In [78]:
array.sort(axis=1)            #	Sorts axis of array
array

array([[1, 3, 3],
       [4, 6, 6]])

In [125]:
array  = np.array([(1,6,3),(4,3,6)])
array2  = np.array([(11,16,13),(14,17,26)])

In [94]:
np.concatenate((array,array2),axis = 0)       #	Concatenates 2 arrays, adds to end

array([[ 1,  6,  3],
       [ 4,  3,  6],
       [11, 16, 13],
       [14, 17, 26]])

In [95]:
np.vstack((array,array2))               #	Stack array row-wise

array([[ 1,  6,  3],
       [ 4,  3,  6],
       [11, 16, 13],
       [14, 17, 26]])

In [105]:
np.hstack((array,array2))           #	Stack array column wise


array([[ 1,  6,  3, 11, 16, 13],
       [ 4,  3,  6, 14, 17, 26]])

In [108]:
x = np.arange(8.0)           # create an arrayend upto 8.0
x

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [113]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])                  #	Split an array into multiple sub-arrays.

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [114]:
np.array_split(x, 3)                 #	Split an array in sub-arrays of (nearly) identical size

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [128]:
np.hsplit(array, 3)            #	Split the array horizontally at 3rd index

[array([[1],
        [4]]),
 array([[6],
        [3]]),
 array([[3],
        [6]])]

In [4]:
import numpy as np

In [6]:
np.__version__

'1.24.3'

In [7]:
l1 =  [12.23, 13.32, 100, 36.32]
np.array(l1)

array([ 12.23,  13.32, 100.  ,  36.32])

In [10]:
arr= np.random.randint(1,11,3)
arr

array([5, 8, 2])