In [1]:
import numpy as np
import math

#### numpy is used to work on array's/ matrix

In [93]:
cp = [200,300,230,400,600]
sp=[345,360,200,410,640]
item=['a','b','c','d','e']

In [88]:
cp = ['200','300','230','400','600']


In [89]:
cp1=np.array(cp)

In [90]:
cp1

array(['200', '300', '230', '400', '600'], dtype='<U3')

In [94]:
cp1=np.array(cp)
sp1=np.array(sp)

In [95]:
(sp1-cp1)*100/cp1      #percentage of profit and loss

array([ 72.5       ,  20.        , -13.04347826,   2.5       ,
         6.66666667])

In [96]:
type(cp1)         ### #numpy.ndarray means n-dimensional array in numpy library

numpy.ndarray

In [97]:
len(cp1)

5

In [5]:
np.prod([2,5])

10

In [5]:
def table(n):
    for i in range(1,11):
        print(n, '*',i, '= ', n*i)

In [ ]:
table(3)

In [98]:
arr1 = np.array([10,23,34,11,67,78,90,43,100])

In [99]:
arr1.shape

(9,)

In [100]:
arr1.reshape(3,3)

array([[ 10,  23,  34],
       [ 11,  67,  78],
       [ 90,  43, 100]])

In [101]:
arr2=arr1.reshape(3,3)

In [102]:
arr2

array([[ 10,  23,  34],
       [ 11,  67,  78],
       [ 90,  43, 100]])

In [103]:
arr1 = np.array([10,23,34,1,67,78,90,43,100,55,658,85,25,65])

In [104]:
arr1.max()

658

In [105]:
arr1.min()

1

In [106]:
arr1.argmax()       ## index position of Max value

10

In [107]:
arr1.argmin()      ## index position of min value

3

In [108]:
arr2

array([[ 10,  23,  34],
       [ 11,  67,  78],
       [ 90,  43, 100]])

In [109]:
arr2.argmax(axis=1)             ### it will give the index position for eagand every row where max value is appearing

array([2, 2, 2], dtype=int64)

In [110]:
arr2.argmin(axis=1)             ### it will give the index position for eagand every row where min value is appearing

array([0, 0, 1], dtype=int64)

In [111]:
### Multiple ways of unique

In [112]:
item=['a','b','c','d','e','e','a','b']

In [113]:
np.unique(item)

array(['a', 'b', 'c', 'd', 'e'], dtype='<U1')

In [114]:
np.power(5,3)

125

In [115]:
np.exp(1)       ## e to the the power 1

2.718281828459045

In [116]:
np.log10(100)

2.0

In [117]:
np.log(2.718281828459045)

1.0

In [118]:
np.abs(-12)

12

In [119]:
np.floor(23.67)

23.0

In [120]:
np.ceil(23.67)

24.0

In [122]:
np.random.randint(1,20,3)            ### it will create random number between 1st two values given and 3rd position is 
                                     ### indicating the no. of values he is giving

array([ 5, 19,  7])

In [123]:
arr=np.random.randint(100,200,2) 
arr

array([197, 187])

In [124]:
arr

array([197, 187])

In [125]:
num1 = np.linspace(1,10,100)              ## creating num between 1 to 10 at regular interval 
                                          ## like if you minus any two numbers the diff will be same
num1

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [126]:
arr= np.eye(5)                    ## identity matrix is square matrix whose diagonal elements are 1 and all other are 0 
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [127]:
a=np.array([1,2,3])
b=np.array([44,55,66])
print("Horizontal Append : ", np.hstack((a,b)))               ## will give horizontal stack or array  

Horizontal Append :  [ 1  2  3 44 55 66]


In [128]:
print("Vertical Append : ", np.vstack((a,b)))                ## will give vertical stack or array

Vertical Append :  [[ 1  2  3]
 [44 55 66]]


In [129]:
num2= np.random.normal(1,2,200)                    ## Normal distribution
num2

array([ 2.49492470e+00,  5.97903535e-01,  4.01515636e-01,  1.94293000e+00,
        2.55637030e+00,  3.57949698e-01,  1.40247299e+00,  4.23561008e+00,
        1.79681190e+00,  2.24340488e+00,  1.80340951e+00,  2.64382007e+00,
        8.77499893e-01,  1.89006911e+00,  1.43651064e+00,  1.98172029e+00,
       -1.14628672e+00,  4.00860977e+00,  2.32346629e+00,  4.58554253e+00,
        1.85933424e+00,  1.83804198e+00,  3.35873309e+00,  2.65878546e+00,
        1.92895235e+00,  2.92491726e+00,  2.02719393e+00,  8.54404844e-01,
        2.85427304e+00,  4.10789162e+00, -4.46374641e+00, -1.54717224e+00,
       -6.99251073e-01, -2.20956887e+00,  9.00851661e-01, -2.63482967e-01,
        6.26695341e+00,  7.32319985e+00,  2.93998432e+00,  1.06955940e+00,
       -3.69071707e+00,  5.46048594e-01,  1.86603001e+00,  1.94918681e-01,
        1.86137783e+00, -3.47510787e-01,  3.86482708e-01,  2.14860747e+00,
       -1.86263950e-02, -4.74554955e-01, -2.04160575e+00,  1.13197454e+00,
       -8.87827648e-01, -

In [ ]:
num2.std()

In [ ]:
num2.mean()

In [ ]:
import matplotlib.pyplot as plt
import seaborn           as sns

In [ ]:
plt.hist(num2,bins=30,edgecolor='cyan');

In [ ]:
import math

In [ ]:
math.factorial(5)

In [ ]:
math.gcd(10,25)              ## gives highest divisible number

In [ ]:
math.sin(50)

In [12]:
import pandas as pd
import numpy as np
mc=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\Mtcars.csv")

In [13]:
mc.head(2)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [14]:
mc['milage'] = np.where(mc.mpg>=20,'Goodavg','Lowavg')

In [15]:
mc

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb   milage
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4  Goodavg
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4  Goodavg
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1  Goodavg
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1  Goodavg
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2   Lowavg
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1   Lowavg
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4   Lowavg
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2  Goodavg
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2  Goodavg
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4   Lowavg
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4   Lowavg
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3   Lowavg
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3   Lowavg
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3   Lowavg
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4   Lowavg
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4   Lowavg
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4   Lowavg
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1  Goodavg
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2  Goodavg
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1  Goodavg
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1  Goodavg
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2   Lowavg
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2   Lowavg
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4   Lowavg
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2   Lowavg
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1  Goodavg
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2  Goodavg
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2  Goodavg
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4   Lowavg
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6   Lowavg
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8   Lowavg
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2  Goodavg

In [16]:
mc['mpg_cat'] = np.where(mc.mpg>=20 ,1,0)        ### it will assign 1 to first name i.e good avg and second is 0 to second name
mc

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb   milage  \
0   21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4  Goodavg   
1   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4  Goodavg   
2   22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1  Goodavg   
3   21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1  Goodavg   
4   18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2   Lowavg   
5   18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1   Lowavg   
6   14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4   Lowavg   
7   24.4    4  146.7   62  3.69  3.190  20.00   1   0     4     2  Goodavg   
8   22.8    4  140.8   95  3.92  3.150  22.90   1   0     4     2  Goodavg   
9   19.2    6  167.6  123  3.92  3.440  18.30   1   0     4     4   Lowavg   
10  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4     4   Lowavg   
11  16.4    8  275.8  180  3.07  4.070  17.40   0   0     3     3   Lowavg   
12  17.3    8  275.8  180  3.07  3.730  17.60   0   0     3     3   Lowavg   
13  15.2    8  275.8  180  3.07  3.780  18.00   0   0     3     3   Lowavg   
14  10.4    8  472.0  205  2.93  5.250  17.98   0   0     3     4   Lowavg   
15  10.4    8  460.0  215  3.00  5.424  17.82   0   0     3     4   Lowavg   
16  14.7    8  440.0  230  3.23  5.345  17.42   0   0     3     4   Lowavg   
17  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4     1  Goodavg   
18  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4     2  Goodavg   
19  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4     1  Goodavg   
20  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3     1  Goodavg   
21  15.5    8  318.0  150  2.76  3.520  16.87   0   0     3     2   Lowavg   
22  15.2    8  304.0  150  3.15  3.435  17.30   0   0     3     2   Lowavg   
23  13.3    8  350.0  245  3.73  3.840  15.41   0   0     3     4   Lowavg   
24  19.2    8  400.0  175  3.08  3.845  17.05   0   0     3     2   Lowavg   
25  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4     1  Goodavg   
26  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5     2  Goodavg   
27  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5     2  Goodavg   
28  15.8    8  351.0  264  4.22  3.170  14.50   0   1     5     4   Lowavg   
29  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5     6   Lowavg   
30  15.0    8  301.0  335  3.54  3.570  14.60   0   1     5     8   Lowavg   
31  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4     2  Goodavg   

    mpg_cat  
0         1  
1         1  
2         1  
3         1  
4         0  
5         0  
6         0  
7         1  
8         1  
9         0  
10        0  
11        0  
12        0  
13        0  
14        0  
15        0  
16        0  
17        1  
18        1  
19        1  
20        1  
21        0  
22        0  
23        0  
24        0  
25        1  
26        1  
27        1  
28        0  
29        0  
30        0  
31        1

In [25]:

mc=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\Mtcars.csv")

In [22]:
corr_list = []
for col in mc.columns[1::]:       # correlation without mpg on mpg
    
    corr_list.append(mc.mpg.corr(mc[col]))
corr_list

[-0.8521619594266131,
 -0.8475513792624786,
 -0.7761683718265863,
 0.6811719078067492,
 -0.8676593765172279,
 0.4186840339217782,
 0.6640389191275927,
 0.5998324294546479,
 0.4802847573388421,
 -0.5509250739024587]

In [28]:
corr_list = []
for i in mc.columns:
    a = mc.mpg.corr(mc[i])
    corr_list.append(a)
corr_list

[1.0,
 -0.8521619594266131,
 -0.8475513792624786,
 -0.7761683718265863,
 0.6811719078067492,
 -0.8676593765172279,
 0.4186840339217782,
 0.6640389191275927,
 0.5998324294546479,
 0.4802847573388421,
 -0.5509250739024587]

In [35]:
df = pd.DataFrame(corr_list)
df.index = mc.columns
df.columns = ['correlation']
df.sort_values(['correlation'], ascending = False)

correlation
mpg      1.000000
drat     0.681172
vs       0.664039
am       0.599832
gear     0.480285
qsec     0.418684
carb    -0.550925
hp      -0.776168
disp    -0.847551
cyl     -0.852162
wt      -0.867659

# Feature selection

In [27]:
l1 = []

for i in mc.columns:
    var1= mc.mpg.corr(mc[i])
    l1.append(var1)
l1  

[1.0,
 -0.8521619594266131,
 -0.8475513792624786,
 -0.7761683718265863,
 0.6811719078067492,
 -0.8676593765172279,
 0.4186840339217782,
 0.6640389191275927,
 0.5998324294546479,
 0.4802847573388421,
 -0.5509250739024587]

### Create dataframe of feature with corr_list

In [28]:
corr_def= pd.DataFrame()

In [31]:
corr_def['columns']=mc.columns
corr_def['corr']=l1

In [32]:
corr_def

columns      corr
0      mpg  1.000000
1      cyl -0.852162
2     disp -0.847551
3       hp -0.776168
4     drat  0.681172
5       wt -0.867659
6     qsec  0.418684
7       vs  0.664039
8       am  0.599832
9     gear  0.480285
10    carb -0.550925

In [33]:
corr_def= pd.DataFrame()

corr_def['columns']=mc.columns
corr_def['corr']=l1

corr_def.sort_values('corr',ascending=False)

columns      corr
0      mpg  1.000000
4     drat  0.681172
7       vs  0.664039
8       am  0.599832
9     gear  0.480285
6     qsec  0.418684
10    carb -0.550925
3       hp -0.776168
2     disp -0.847551
1      cyl -0.852162
5       wt -0.867659

In [34]:
mc=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\Mtcars.csv")
mc.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [35]:
mc.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='object')

In [36]:
l1=[]

for i in mc.columns:
    l1.append(mc.mpg.corr(mc[i]))
  

In [37]:
l1

[1.0,
 -0.8521619594266131,
 -0.8475513792624786,
 -0.7761683718265863,
 0.6811719078067492,
 -0.8676593765172279,
 0.4186840339217782,
 0.6640389191275927,
 0.5998324294546479,
 0.4802847573388421,
 -0.5509250739024587]

In [38]:
corr_def= pd.DataFrame()

In [39]:
corr_def['columns']=mc.columns
corr_def['corr']=l1


In [40]:
l1=[]
for i in mc.columns:
    l1.append(mc.mpg.corr(mc[i]))

In [41]:
# l1

In [42]:
df=pd.DataFrame()
df['columns']=mc.columns
df['corr_mpg']=l1
df1=df[df.corr_mpg>0.5]

In [43]:
df1

columns  corr_mpg
0     mpg  1.000000
4    drat  0.681172
7      vs  0.664039
8      am  0.599832

In [44]:
import pandas as pd
bf=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\bodyfat.csv")

In [45]:
bf.head()

Bodyfat  Age  Weight  Height  Neck  Chest  Abdomen  Ankle  Biceps  Wrist
0     32.3   41  247.25   73.50  42.1  117.0    115.6   26.3    37.3   19.7
1     22.5   31  177.25   71.50  36.2  101.1     92.4   24.6    30.1   18.2
2     22.0   42  156.25   69.00  35.5   97.8     86.0   24.0    31.2   17.4
3     12.3   23  154.25   67.75  36.2   93.1     85.2   21.9    32.0   17.1
4     20.5   46  177.00   70.00  37.2   99.7     95.6   22.5    29.1   17.7

In [46]:
bf.columns

Index(['Bodyfat', 'Age', 'Weight', 'Height', 'Neck', 'Chest', 'Abdomen',
       'Ankle', 'Biceps', 'Wrist'],
      dtype='object')

In [53]:
l1=[]

for i in bf.columns:
   
    l1.append(bf.Bodyfat.corr( bf[i])>0.5)
l1

[True, False, True, False, True, True, True, False, False, False]

In [54]:
corr_def= pd.DataFrame()

In [55]:
corr_def['column']=bf.columns
corr_def['corr']=l1

In [56]:
corr_def

column   corr
0  Bodyfat   True
1      Age  False
2   Weight   True
3   Height  False
4     Neck   True
5    Chest   True
6  Abdomen   True
7    Ankle  False
8   Biceps  False
9    Wrist  False

#### CUT

In [57]:
cr=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\CreditRisk.csv")

In [83]:
abc=pd.cut(cr.ApplicantIncome,bins=[0,20000,40000,81000],labels=['low','medium','high'])
       # 0---20000--->low including 20000
        # 20001---40000----> medium
        #40001-- 81000----> high

In [80]:
abc.value_counts()

ApplicantIncome
low       963
medium     12
high        4
Name: count, dtype: int64

In [81]:
cr['Income_cat']=abc

In [82]:
cr

Loan_ID  Gender Married  Dependents     Education Self_Employed  \
0    LP001002    Male      No         0.0      Graduate            No   
1    LP001003    Male     Yes         1.0      Graduate            No   
2    LP001005    Male     Yes         0.0      Graduate           Yes   
3    LP001006    Male     Yes         0.0  Not Graduate            No   
4    LP001008    Male      No         0.0      Graduate            No   
5    LP001011    Male     Yes         2.0      Graduate           Yes   
6    LP001013    Male     Yes         0.0  Not Graduate            No   
7    LP001014    Male     Yes         4.0      Graduate            No   
8    LP001018    Male     Yes         2.0      Graduate            No   
9    LP001020    Male     Yes         1.0      Graduate            No   
10   LP001024    Male     Yes         2.0      Graduate            No   
11   LP001027    Male     Yes         2.0      Graduate           NaN   
12   LP001028    Male     Yes         2.0      Graduate            No   
13   LP001029    Male      No         0.0      Graduate            No   
14   LP001030    Male     Yes         2.0      Graduate            No   
15   LP001032    Male      No         0.0      Graduate            No   
16   LP001034    Male      No         1.0  Not Graduate            No   
17   LP001036  Female      No         0.0      Graduate            No   
18   LP001038    Male     Yes         0.0  Not Graduate            No   
19   LP001041    Male     Yes         0.0      Graduate           NaN   
20   LP001043    Male     Yes         0.0  Not Graduate            No   
21   LP001046    Male     Yes         1.0      Graduate            No   
22   LP001047    Male     Yes         0.0  Not Graduate            No   
23   LP001050     NaN     Yes         2.0  Not Graduate            No   
24   LP001052    Male     Yes         1.0      Graduate           NaN   
25   LP001066    Male     Yes         0.0      Graduate           Yes   
26   LP001068    Male     Yes         0.0      Graduate            No   
27   LP001073    Male     Yes         2.0  Not Graduate            No   
28   LP001086    Male      No         0.0  Not Graduate            No   
29   LP001087  Female      No         2.0      Graduate           NaN   
30   LP001091    Male     Yes         1.0      Graduate           NaN   
31   LP001095    Male      No         0.0      Graduate            No   
32   LP001097    Male      No         1.0      Graduate           Yes   
33   LP001098    Male     Yes         0.0      Graduate            No   
34   LP001100    Male      No         4.0      Graduate            No   
35   LP001106    Male     Yes         0.0      Graduate            No   
36   LP001109    Male     Yes         0.0      Graduate            No   
37   LP001112  Female     Yes         0.0      Graduate            No   
38   LP001114    Male      No         0.0      Graduate            No   
39   LP001116    Male      No         0.0  Not Graduate            No   
40   LP001119    Male      No         0.0      Graduate            No   
41   LP001120    Male      No         0.0      Graduate            No   
42   LP001123    Male     Yes         0.0      Graduate            No   
43   LP001131    Male     Yes         0.0      Graduate            No   
44   LP001136    Male     Yes         0.0  Not Graduate           Yes   
45   LP001137  Female      No         0.0      Graduate            No   
46   LP001138    Male     Yes         1.0      Graduate            No   
47   LP001144    Male     Yes         0.0      Graduate            No   
48   LP001146  Female     Yes         0.0      Graduate            No   
49   LP001151  Female      No         0.0      Graduate            No   
50   LP001155  Female     Yes         0.0  Not Graduate            No   
51   LP001157  Female      No         0.0      Graduate            No   
52   LP001164  Female      No         0.0      Graduate            No   
53   LP001179    Male     Yes         2.0      Graduate         

In [7]:
import pandas as pd
ppt=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\Property_Price_Train.csv")
ppt

Id  Building_Class Zoning_Class  Lot_Extent  Lot_Size Road_Type  \
0        1              60          RLD        65.0      8450     Paved   
1        2              20          RLD        80.0      9600     Paved   
2        3              60          RLD        68.0     11250     Paved   
3        4              70          RLD        60.0      9550     Paved   
4        5              60          RLD        84.0     14260     Paved   
...    ...             ...          ...         ...       ...       ...   
1454  1455              20          FVR        62.0      7500     Paved   
1455  1456              60          RLD        62.0      7917     Paved   
1456  1457              20          RLD        85.0     13175     Paved   
1457  1458              70          RLD        66.0      9042     Paved   
1458  1459              20          RLD        68.0      9717     Paved   

     Lane_Type Property_Shape Land_Outline Utility_Type  ... Pool_Area  \
0          NaN            Reg          Lvl       AllPub  ...         0   
1          NaN            Reg          Lvl       AllPub  ...         0   
2          NaN            IR1          Lvl       AllPub  ...         0   
3          NaN            IR1          Lvl       AllPub  ...         0   
4          NaN            IR1          Lvl       AllPub  ...         0   
...        ...            ...          ...          ...  ...       ...   
1454     Paved            Reg          Lvl       AllPub  ...         0   
1455       NaN            Reg          Lvl       AllPub  ...         0   
1456       NaN            Reg          Lvl       AllPub  ...         0   
1457       NaN            Reg          Lvl       AllPub  ...         0   
1458       NaN            Reg          Lvl       AllPub  ...         0   

     Pool_Quality Fence_Quality Miscellaneous_Feature Miscellaneous_Value  \
0             NaN           NaN                   NaN                   0   
1             NaN           NaN                   NaN                   0   
2             NaN           NaN                   NaN                   0   
3             NaN           NaN                   NaN                   0   
4             NaN           NaN                   NaN                   0   
...           ...           ...                   ...                 ...   
1454          NaN           NaN                   NaN                   0   
1455          NaN           NaN                   NaN                   0   
1456          NaN         MnPrv                   NaN                   0   
1457          NaN         GdPrv                  Shed                2500   
1458          NaN           NaN                   NaN                   0   

     Month_Sold Year_Sold  Sale_Type  Sale_Condition  Sale_Price  
0             2      2008         WD          Normal      208500  
1             5      2007         WD          Normal      181500  
2             9      2008         WD          Normal      223500  
3             2      2006         WD         Abnorml      140000  
4            12      2008         WD          Normal      250000  
...         ...       ...        ...             ...         ...  
1454         10      2009         WD          Normal      185000  
1455          8      2007         WD          Normal      175000  
1456          2      2010         WD          Normal      210000  
1457          5      2010         WD          Normal      266500  
1458          4      2010         WD          Normal      142125  

[1459 rows x 81 columns]

  ### find percentage nulls                              

In [84]:
ppt.isnull().sum()[ppt.isnull().sum()>0]*100/ppt.shape[0]

Lot_Extent               17.751885
Lane_Type                93.762851
Brick_Veneer_Type        59.698424
Brick_Veneer_Area         0.548321
Basement_Height           2.535984
Basement_Condition        2.535984
Exposure_Level            2.604524
BsmtFinType1              2.535984
BsmtFinType2              2.604524
Electrical_System         0.068540
Fireplace_Quality        47.224126
Garage                    5.551748
Garage_Built_Year         5.551748
Garage_Finish_Year        5.551748
Garage_Quality            5.551748
Garage_Condition          5.551748
Pool_Quality             99.520219
Fence_Quality            80.740233
Miscellaneous_Feature    96.298835
dtype: float64

### find those col which have 50% of nulls

In [10]:
ppt.isnull().sum()[ppt.isnull().sum()>0]*100/ppt.shape[0]


Lot_Extent               17.751885
Lane_Type                93.762851
Brick_Veneer_Type        59.698424
Brick_Veneer_Area         0.548321
Basement_Height           2.535984
Basement_Condition        2.535984
Exposure_Level            2.604524
BsmtFinType1              2.535984
BsmtFinType2              2.604524
Electrical_System         0.068540
Fireplace_Quality        47.224126
Garage                    5.551748
Garage_Built_Year         5.551748
Garage_Finish_Year        5.551748
Garage_Quality            5.551748
Garage_Condition          5.551748
Pool_Quality             99.520219
Fence_Quality            80.740233
Miscellaneous_Feature    96.298835
dtype: float64

In [19]:
df =pd.DataFrame(ppt.isnull().sum()[ppt.isnull().sum()>0]*100/ppt.shape[0]) 
df.columns = ['Per_null']
df.sort_values(['Per_null'], ascending = False)
df[df.Per_null >= 50]

Per_null
Lane_Type              93.762851
Brick_Veneer_Type      59.698424
Pool_Quality           99.520219
Fence_Quality          80.740233
Miscellaneous_Feature  96.298835

## feature selection on ppt

In [20]:
ppt=pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\New folder\Property_Price_Train.csv")
ppt

Id  Building_Class Zoning_Class  Lot_Extent  Lot_Size Road_Type  \
0        1              60          RLD        65.0      8450     Paved   
1        2              20          RLD        80.0      9600     Paved   
2        3              60          RLD        68.0     11250     Paved   
3        4              70          RLD        60.0      9550     Paved   
4        5              60          RLD        84.0     14260     Paved   
...    ...             ...          ...         ...       ...       ...   
1454  1455              20          FVR        62.0      7500     Paved   
1455  1456              60          RLD        62.0      7917     Paved   
1456  1457              20          RLD        85.0     13175     Paved   
1457  1458              70          RLD        66.0      9042     Paved   
1458  1459              20          RLD        68.0      9717     Paved   

     Lane_Type Property_Shape Land_Outline Utility_Type  ... Pool_Area  \
0          NaN            Reg          Lvl       AllPub  ...         0   
1          NaN            Reg          Lvl       AllPub  ...         0   
2          NaN            IR1          Lvl       AllPub  ...         0   
3          NaN            IR1          Lvl       AllPub  ...         0   
4          NaN            IR1          Lvl       AllPub  ...         0   
...        ...            ...          ...          ...  ...       ...   
1454     Paved            Reg          Lvl       AllPub  ...         0   
1455       NaN            Reg          Lvl       AllPub  ...         0   
1456       NaN            Reg          Lvl       AllPub  ...         0   
1457       NaN            Reg          Lvl       AllPub  ...         0   
1458       NaN            Reg          Lvl       AllPub  ...         0   

     Pool_Quality Fence_Quality Miscellaneous_Feature Miscellaneous_Value  \
0             NaN           NaN                   NaN                   0   
1             NaN           NaN                   NaN                   0   
2             NaN           NaN                   NaN                   0   
3             NaN           NaN                   NaN                   0   
4             NaN           NaN                   NaN                   0   
...           ...           ...                   ...                 ...   
1454          NaN           NaN                   NaN                   0   
1455          NaN           NaN                   NaN                   0   
1456          NaN         MnPrv                   NaN                   0   
1457          NaN         GdPrv                  Shed                2500   
1458          NaN           NaN                   NaN                   0   

     Month_Sold Year_Sold  Sale_Type  Sale_Condition  Sale_Price  
0             2      2008         WD          Normal      208500  
1             5      2007         WD          Normal      181500  
2             9      2008         WD          Normal      223500  
3             2      2006         WD         Abnorml      140000  
4            12      2008         WD          Normal      250000  
...         ...       ...        ...             ...         ...  
1454         10      2009         WD          Normal      185000  
1455          8      2007         WD          Normal      175000  
1456          2      2010         WD          Normal      210000  
1457          5      2010         WD          Normal      266500  
1458          4      2010         WD          Normal      142125  

[1459 rows x 81 columns]

In [21]:
ppt.columns

Index(['Id', 'Building_Class', 'Zoning_Class', 'Lot_Extent', 'Lot_Size',
       'Road_Type', 'Lane_Type', 'Property_Shape', 'Land_Outline',
       'Utility_Type', 'Lot_Configuration', 'Property_Slope', 'Neighborhood',
       'Condition1', 'Condition2', 'House_Type', 'House_Design',
       'Overall_Material', 'House_Condition', 'Construction_Year',
       'Remodel_Year', 'Roof_Design', 'Roof_Quality', 'Exterior1st',
       'Exterior2nd', 'Brick_Veneer_Type', 'Brick_Veneer_Area',
       'Exterior_Material', 'Exterior_Condition', 'Foundation_Type',
       'Basement_Height', 'Basement_Condition', 'Exposure_Level',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'Total_Basement_Area', 'Heating_Type', 'Heating_Quality',
       'Air_Conditioning', 'Electrical_System', 'First_Floor_Area',
       'Second_Floor_Area', 'LowQualFinSF', 'Grade_Living_Area',
       'Underground_Full_Bathroom', 'Underground_Half_Bathroom',
       'Full_Bathroom_Above_Grade', 'Ha

In [ ]:
df=pd.DataFrame(ppt.isnull().sum()[ppt.isnull().sum()>0]*100/ppt.shape[0])


In [ ]:
df.columns=['per_nulls']
df[df.per_nulls >= 50]

In [ ]:
df.columns=['per_nulls']
df[df.per_nulls >= 50].index

In [ ]:
cr.head()

In [ ]:
cr.isnull().sum()

In [ ]:
cr.Gender.fillna('Male',inplace=True)

In [ ]:
cr.Gender.value_counts()

In [ ]:
cr.loc[cr.Gender=='Male','New_col']=0
cr.loc[cr.Gender=='Female','New_col']=1

In [ ]:
cr.tail(10)

### There are three methods to convert non numeric data numeric
1. replace
2. label_encoder
3. One hot coding
4. create num column

In [ ]:
## there are three methods to convert non numeric data numeric 
## replace 
## label_encoder
## one hot coding
## create num column
